### ISSUE TITLE
baudrate error

### ISSUE THREAD

**Issue by RobertTurner2** [vanviegen/hue-thief#2]
install on Raspbian-Stretch using Nortec HUSBZB-1
i get 
Traceback (most recent call last):
  File "hue-thief.py, line 124, in <module>
    loop.run_until_complete(steal(sys.argv[1]))
  File "user/lib/python3.5/asyncio/base_events.py", line 293, in result
    rase self._exception
   File "user/lib/python3.5/asyncio/tasks.py", line 239, in_step
    result = coro.send(none)
  File "hue-thief.py", line 28 in steal
    s= yield from util.setup(device)
TypeError: setup() missing 1 required positional argument: 'baudrate'

**Comment by kalliste** [comment]
Looks like this broke it https://github.com/rcloran/bellows/pull/41
