### ISSUE TITLE
Timeout error during setup

### ISSUE THREAD

**Issue by stuaxo** [vanviegen/hue-thief#26]
I'm running this on my Ubuntu laptop and get a timeout error during setup:

```
$  python hue-thief.py /dev/ttyUSB0

Traceback (most recent call last):
  File "/home/stu/.virtualenvs/hue-thief/lib/python3.11/site-packages/bellows/cli/util.py", line 113, in setup
    await s._startup_reset()
  File "/home/stu/.virtualenvs/hue-thief/lib/python3.11/site-packages/bellows/ezsp/__init__.py", line 103, in _startup_reset
    await self.reset()
  File "/home/stu/.virtualenvs/hue-thief/lib/python3.11/site-packages/bellows/ezsp/__init__.py", line 132, in reset
    await self._gw.reset()
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stu/projects/external/iot/hue/hue-thief/hue-thief.py", line 135, in <module>
    asyncio.get_event_loop().run_until_complete(steal(args.device, args.baudrate, args.channel))
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/stu/projects/external/iot/hue/hue-thief/hue-thief.py", line 28, in steal
    dev = await util.setup(device_path, baudrate)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stu/.virtualenvs/hue-thief/lib/python3.11/site-packages/bellows/cli/util.py", line 117, in setup
    raise click.Abort()
click.exceptions.Abort

```

```
$ ❯ lsusb | grep CP210x
Bus 001 Device 002: ID 10c4:ea60 Silicon Labs CP210x UART Bridge
```

**Comment by Blackspell01** [comment]
did you find out what the culprit was?

**Comment by RauliL** [comment]
I could bypass this error by setting baudrate to 115200 but got stuck with some kind of mfglib error.

**Comment by stuaxo** [comment]
> did you find out what the culprit was?

I didn't get any further.

> I could bypass this error by setting baudrate to 115200 but got stuck with some kind of mfglib error.

I'll give that a go + see if I can at least reproduce the error and post it here.
