### ISSUE TITLE
Timeout Error during Communication with Bulb

### ISSUE THREAD

**Issue by Chopium** [vanviegen/hue-thief#27]
```
Scanning on channel 20
NCP entered failed state. Requesting APP controller restart
Traceback (most recent call last):
  File "/home/colter/.local/lib/python3.10/site-packages/bellows/ezsp/protocol.py", line 152, in command
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/colter/hue-thief/hue-thief.py", line 135, in <module>
    asyncio.get_event_loop().run_until_complete(steal(args.device, args.baudrate, args.channel))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/colter/hue-thief/hue-thief.py", line 105, in steal
    await dev.mfglibSendPacket(frame)
  File "/home/colter/.local/lib/python3.10/site-packages/bellows/ezsp/protocol.py", line 151, in command
    async with asyncio_timeout(EZSP_CMD_TIMEOUT):
  File "/home/colter/.local/lib/python3.10/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/home/colter/.local/lib/python3.10/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

I had my hue bulbs paired to a usb sonoff zigbee adaptor via Home Assistant but had a usb path break and need to reset all the bulbs. Some accepted the power cycle reset method, but a handful will not. Attempting to do this touchlink reset method, it appears promising because the bulbs are detected and flash, but the process seems to fail to get a response back from the bulb?

**Comment by Blackspell01** [comment]
have you found a solution?

**Comment by stuaxo** [comment]
No, since this particular lamp didn't need to be on the same system as everything else I bought a second hand older hue control and was able reset the lamp with it and control it from there.

While that didn't get things working with hue thief it meant I could at least use the lamp.

**Comment by Chopium** [comment]
Nope. I pulled out the hue hub thing to do the resets. 
You can initiate a factory reset using the bulb's serial number in the hue app if you have the bridge.

I don't recall if hue-thief did anything for me in the end. The tough bulbs needed the bridge to reset.

**Comment by Blackspell01** [comment]
I was able to reset my two play bars with zigbee2mqtt using the touchlink tab :). Interestingly the firmware my sonoff dongle e which was preindtalled didn't come with touchlink activated, therefore I had to flash an unofficial firmware first. Since I don't have any other hue device, this came in very handy for me!
